maxio-com/stoplight-platform-api-docs

- reference/Chargify-API.v1.yaml
Related PR: https://github.com/maxio-com/chargify/pull/22173
> [documentation] Add docs for `request_payment_profiles_update` endpoint

- reference/Chargify-API.v1.yaml
Adding ``direction`` parameter to provide sorting option for List Metadata for Resource Type API endpoint
https://chargify.atlassian.net/browse/FRI-1040
> [documentation] Add direction param to List Metadata for Resource Type

- reference/Chargify-API.v1.yaml
**Jira Task:**
https://chargify.atlassian.net/browse/CB-2757
**Description:**
Added missing documentation about compounding strategy coupons for ad hoc invoices.
> added compounding_strategy description to coupons

- reference/Chargify-API.v1.yaml
Adding direction parameter to provide sorting option for List Metafields API endpoint
https://chargify.atlassian.net/browse/SUBB-201
> [documentation] Add direction param to List Metafields API endpoint

- models/Subscription.yaml
- reference/Chargify-API.v1.yaml
https://chargify.atlassian.net/browse/CB-2762
> [documentation] Enhance GET Subscription endpoint with coupon data

- reference/Chargify-API.v1.yaml
Reference link: https://chargify.atlassian.net/browse/SUB-2499
> SUB-2499: Add response example

- reference/Chargify-API.v1.yaml
- reference/Chargify-Legacy-API.yaml
Updating broken URL navigations due to ZD migration
> [fix] broken URL

- models/Subscription.yaml
Added product_price_point_type for Subscription respond body
https://maxioevolution.atlassian.net/browse/SUB-2826
> [Update] Added product_price_point_type for Subscription respond body

- .github/workflows/build-sdk.yml
- .github/workflows/publish-sdk.yml
[DE-248] DE-258 Add pipeline for publishing sdks
[DE-248]: https://maxioevolution.atlassian.net/browse/DE-248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DE-248] DE-258 Add pipeline for publishing sdks

- reference/Chargify-API.v1.yaml
Updated response for /site.json and /subscriptions_components.json endpoints
https://maxioevolution.atlassian.net/browse/SUB-2971
> [documentation] Updated response for /site.json and subscriptions_components.json endpoints

- models/Payment-Profile.yaml
- models/Product.yaml
- reference/Chargify-API.v1.yaml
This PR fixes all errors and warnings showed in Stoplight:
- fix nullable properties
- fix examples
- reuse page/per_page parameter
- add missing tags
> [DE-248] DE-399 Fix errors/warning in Stoplight

- components/schemas/Bank-Account-Payment-Profile.yaml
- components/schemas/Bank-Account-Response.yaml
- components/schemas/Bank-Account-Verification-Request.yaml
- components/schemas/Bank-Account-Verification.yaml
- components/schemas/Bank-Account.yaml
- components/schemas/Create-Payment-Profile-Request.yaml
- components/schemas/Create-Payment-Profile-Response.yaml
- components/schemas/Create-Payment-Profile-Vault.yaml
- components/schemas/Create-Payment-Profile.yaml
- components/schemas/Created-Payment-Profile.yaml
- components/schemas/Credit-Card-Payment-Profile.yaml
- components/schemas/List-Payment-Profile-Item.yaml
- components/schemas/List-Payment-Profiles-Response.yaml
- components/schemas/List-Payment-Profiles.yaml
- components/schemas/Payment-Type.yaml
- components/schemas/Read-Payment-Profile-Response.yaml
- components/schemas/Update-Payment-Profile-Request.yaml
- components/schemas/Update-Payment-Profile-Response.yaml
- components/schemas/Update-Payment-Profile.yaml
- components/schemas/Updated-Payment-Profile.yaml
- reference/Chargify-API.v1.yaml
[DE-248] DE-432 Extract Bank Account and Payment Profiles
[DE-248]: https://maxioevolution.atlassian.net/browse/DE-248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DE-248] DE-432 Extract Bank Account and Payment Profiles

- reference/Chargify-API.v1.yaml
Excessive section removed. Just that.
Please refer to: https://maxioevolution.atlassian.net/browse/PAYM-608
> [documentation] PAYM-608-Duplicate-sections-in-Create-Subscription-cleanup

- components/schemas/Prepayment-Response.yaml
- components/schemas/Prepayment.yaml
- reference/Chargify-API.v1.yaml
**WHAT?**
- Update types in the `Prepayment` model for `details` and `payment_type`,
- Update the response for `GET /subscriptions/:id/prepayments.json`
> [documentation] Update prepayment response

- reference/Chargify-API.v1.yaml
- fixed broken link online 169 related to advanced billing subscription
- fixed another identified broken link related to webhook configurations
> fixing broken links 

- reference/Chargify-API.v1.yaml
**WHAT?**
Update descriptions and make correct type of array
> [IN-2361] Fix errors and warnings related to invoice events

- components/schemas/Offer-Item.yaml
Add Type ref for `currency_prices` items in `Offer-Item.yaml`
Ref: https://maxioevolution.atlassian.net/browse/SUB-3311
> [SUB-3311] Add currency_prices item type in Offer-Item.yaml

- components/schemas/Allocate-Components.yaml
- components/schemas/Collection-Method.yaml
- components/schemas/Legacy-Collection-Method.yaml
- components/schemas/Signup-Collection-Method.yaml
- components/schemas/Subscription-Group-Signup-Response.yaml
- components/schemas/Subscription-Group-Signup.yaml
https://maxioevolution.atlassian.net/browse/PAYM-762
Indeed there seems to be a good idea to merge `Legacy-Collection-Method.yaml`, `Signup-Collection-Method.yaml` and `Collection-Method.yaml` into one.
> [documentation] PAYM-762 merging Collection-Method schema

- components/schemas/Component-Price.yaml
- components/schemas/Component.yaml
**WHAT?**
Add missing attributes to the component model.
> [documentation] update component models and examples

- reference/Chargify-API.v1.yaml
**WHAT?**
Remove redundant example in trial_ended reactivation sections
> [bug] Remove redundant example in trial_ended reactivation sections

- reference/Chargify-API.v1.yaml
**WHAT?**
Remove consultants from API Docs
> [documentation] remove consultants from API Docs

- components/schemas/Create-Customer.yaml
**WHAT?**
Add missing `parent_id`
> [documentation] Add missing parent_id to the Create Customer endpoint request body

- components/schemas/Preview-Allocations-Request.yaml
- reference/Chargify-API.v1.yaml
According to the following ticket - https://maxioevolution.atlassian.net/browse/SUB-3421, we are adding a new field - `effective_proration_date` - under the Preview Allocations endpoint.
> [SUB-3421] Update Preview Allocations 

- components/schemas/Update-Customer.yaml
This reverts commit bb33ffc591b8d66559ea4fc4d73025fd82c7f840.
> Revert "Add required fields in Update-Customer.yaml (#282)"

- reference/Chargify-API.v1.yaml
Reverts maxio-com/stoplight-platform-api-docs#287
> Revert "Set Collect Parameters property for operations with many parameters"

- components/schemas/errors/Product-Price-Point-Errors.yaml
- reference/Chargify-API.v1.yaml
The generated doc `doc/models/product-price-point-errors.md` will contain:
```
```json
{
"price_point": "can't be blank",
"interval": [
"Recurring Interval: cannot be blank."
"Recurring Interval: must be greater than or equal to 1."
],
"interval_unit": [
"Interval unit: cannot be blank.",
"Interval unit: must be 'month' or 'day'."
],
"name": [
"Name: cannot be blank."
],
"price": [
"Price: is not a number."
"Price: must be greater than or equal to 0."
],
"price_in_cents": [
"Price in cents: cannot be blank."
]
}
```
> [DE-613] - Error responses for Create Product Price Point(s) #2

- components/schemas/Subscription-State-Filter.yaml
- components/schemas/Subscription-State.yaml
- components/schemas/Subscription.yaml
- reference/Chargify-API.v1.yaml
This is how Subscription is rendered in Stoplight after the change:
> [DE-527] DE-620 Add enum for Subscription State

- reference/Chargify-API.v1.yaml
Reverts maxio-com/stoplight-platform-api-docs#335
> Revert "[DE-637] Change operationId for readComponentByHandle to findComponent"

- components/schemas/Coupon.yaml
Update coupon issue,
To solve these errors I add an optional null value for those properties
> DE-598: added null option for update coupon endpoint

- components/schemas/Component-Price-Point-Item.yaml
- components/schemas/Component-Price-Point.yaml
- components/schemas/Component.yaml
- components/schemas/Create-Component-Price-Point.yaml
- components/schemas/Ebb-Component.yaml
- components/schemas/Metered-Component.yaml
- components/schemas/On-Off-Component.yaml
- components/schemas/Quantity-Based-Component.yaml
https://maxioevolution.atlassian.net/browse/SUB-3548
> [SUB-3548] extend component and component price point by interval attributes

- components/schemas/Update-Component-Price-Point.yaml
https://maxioevolution.atlassian.net/browse/SUB-3552
> [SUB-3552] update "update component price point" model

- components/schemas/Component-Custom-Price.yaml
https://maxioevolution.atlassian.net/browse/SUB-3565
https://maxioevolution.atlassian.net/browse/SUB-3563
> [docs] update Update Subscription API

- components/schemas/Subscription-Component.yaml
Ticket refs:
- https://maxioevolution.atlassian.net/browse/SUB-3566
- https://maxioevolution.atlassian.net/browse/SUB-3567
- https://maxioevolution.atlassian.net/browse/SUB-3568
> [SUB-3545] Add interval to subscription components

- components/schemas/Create-Product-Price-Point.yaml
- components/schemas/Create-or-Update-Product.yaml
- components/schemas/Product-Price-Point.yaml
- components/schemas/Product.yaml
> create product and product price_point corrections

- reference/Chargify-API.v1.yaml
- Add query parameters for list subscription group proforma invoices
- Use ProformaInvoiceStatus for list proforma invoices status query parameter
> [DE-744] Add query parameters for list subscription group proforma invoices

- portal/ignored-warnings.txt
- portal/spec/components/parameters/list-components-filter.yaml
- portal/spec/components/parameters/list-coupons-filter.yaml
- portal/spec/components/parameters/list-mrr-filter.yaml
- portal/spec/components/parameters/list-prepayments-filter.yaml
- portal/spec/components/parameters/list-pricepoints-filter.yaml
- portal/spec/components/parameters/list-products-filter.yaml
- portal/spec/components/parameters/list-segments-filter.yaml
- portal/spec/components/parameters/list-subscription-components-filter.yaml
- portal/spec/components/parameters/list-subscription-components-for-site-filter.yaml
- portal/spec/components/schemas/List-Components-Filter.yaml
- portal/spec/components/schemas/List-Coupons-Filter.yaml
- portal/spec/components/schemas/List-Mrr-Filter.yaml
- portal/spec/components/schemas/List-Prepayment-Date-Field.yaml
- portal/spec/components/schemas/List-Prepayments-Filter.yaml
- portal/spec/components/schemas/List-PricePoints-Filter.yaml
- portal/spec/components/schemas/List-Products-Filter.yaml
- portal/spec/components/schemas/List-Segments-Filter.yaml
- portal/spec/components/schemas/List-Subscription-Components-Filter.yaml
- portal/spec/components/schemas/List-Subscription-Components-For-Site-Filter.yaml
- portal/spec/components/schemas/Prepaid-Product-Price-Point-Filter.yaml
- portal/spec/components/schemas/Subscription-Filter.yaml
- portal/spec/openapi.yaml
[DE-770] DE-754 Fix usage of filters and deep objects
Fix [] in parameter names
[DE-770]: https://maxioevolution.atlassian.net/browse/DE-770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DE-770] DE-754 Fix usage of filters and deep objects

- components/schemas/Create-Payment-Profile.yaml
- portal/content/development-tools/chargify-js/configurations.md
- portal/content/development-tools/chargify-js/examples.md
- portal/spec/components/schemas/Create-Payment-Profile.yaml
- portal/spec/openapi.yaml
- reference/Chargify-API.v1.yaml
Add Stripe BACS Direct Debit examples
> [documentation] Add Stripe BACS Direct Debit examples

- components/schemas/Create-Product-Family.yaml
- portal/spec/components/schemas/Create-Product-Family.yaml
its available when creating pf via ui and we even mention handle request param in some introduction docs
> [DE-765] Document handle for product family create

- components/schemas/Historic-Usage.yaml
- portal/spec/components/schemas/Historic-Usage.yaml
**WHAT?**
Update the description of Historic Usage.
https://maxio.slack.com/archives/C0636LP6W2U/p1715858040327679?thread_ts=1715788522.812239&cid=C0636LP6W2U
> [docs] update description for Historic Usage

- components/schemas/Customer.yaml
- portal/spec/components/schemas/Customer.yaml
Reference: https://maxioevolution.atlassian.net/browse/ON-85
Background: https://maxioevolution.atlassian.net/browse/ON-22
> [ON-85] Document default value of customer organization.
